package bootcampou;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Customer Name")
   private java.lang.String custname;
   @org.kie.api.definition.type.Label(value = "Customer ID")
   private java.lang.String custid;
   @org.kie.api.definition.type.Label(value = "HOA Signature milestone")
   private java.lang.Boolean hoasign;
   @org.kie.api.definition.type.Label(value = "Electric Approval")
   private java.lang.Boolean electric;
   @org.kie.api.definition.type.Label(value = "Structural approval")
   private java.lang.Boolean structural;
   @org.kie.api.definition.type.Label(value = "Order Completed")
   private java.lang.Boolean completed;

   public NewOrder()
   {
   }

   public java.lang.String getCustname()
   {
      return this.custname;
   }

   public void setCustname(java.lang.String custname)
   {
      this.custname = custname;
   }

   public java.lang.String getCustid()
   {
      return this.custid;
   }

   public void setCustid(java.lang.String custid)
   {
      this.custid = custid;
   }

   public java.lang.Boolean getHoasign()
   {
      return this.hoasign;
   }

   public void setHoasign(java.lang.Boolean hoasign)
   {
      this.hoasign = hoasign;
   }

   public java.lang.Boolean getElectric()
   {
      return this.electric;
   }

   public void setElectric(java.lang.Boolean electric)
   {
      this.electric = electric;
   }

   public java.lang.Boolean getStructural()
   {
      return this.structural;
   }

   public void setStructural(java.lang.Boolean structural)
   {
      this.structural = structural;
   }

   public java.lang.Boolean getCompleted()
   {
      return this.completed;
   }

   public void setCompleted(java.lang.Boolean completed)
   {
      this.completed = completed;
   }

   public NewOrder(java.lang.String custname, java.lang.String custid,
         java.lang.Boolean hoasign, java.lang.Boolean electric,
         java.lang.Boolean structural, java.lang.Boolean completed)
   {
      this.custname = custname;
      this.custid = custid;
      this.hoasign = hoasign;
      this.electric = electric;
      this.structural = structural;
      this.completed = completed;
   }

}